name: On Commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ./configure
        make -j 4
    - name: Run tests
      run: make -j 4 check
