name: On Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Build
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: |
        ./configure
        make prep
        make -j 4

    - name: Run tests
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: |
        make -j 4 check

    - name: Static Analysis
      if: "github.event.size > 0 && !startsWith(github.event.commits[0].message, 'WIP')"
      if: runner.os == 'macOS' && startsWith(github.ref, 'refs/heads/feature/')
      run: |
        echo ${{ github.event.commits[0].message }}
        make analyze
