name: On Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Build
      if: |
        !startsWith(github.event.head_commit.message, 'WIP')
        && !startsWith(github.ref, 'refs/tags/')
      run: |
        git submodule update --init --recursive
        ./configure
        make prep
        make -j 4

    - name: Run tests
      if: |
        !startsWith(github.event.head_commit.message, 'WIP')
        && !startsWith(github.ref, 'refs/tags/')
      run: |
        make -j 4 check

    - name: Static Analysis
      if: |
        !startsWith(github.event.head_commit.message, 'WIP')
        && runner.os == 'macOS'
        && startsWith(github.ref, 'refs/heads/feature/')
      run: |
        make analyze
