name: On Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Build
      if: |
        github.event.commits
        && !startsWith(github.event.commits[0].message, 'WIP')
        && !startsWith(github.ref, 'refs/tags/')
      run: |
        ./configure
        make prep
        make -j 4

    - name: Run tests
      if: |
        github.event.commits
        && !startsWith(github.event.commits[0].message, 'WIP')
        && !startsWith(github.ref, 'refs/tags/')
      run: |
        make -j 4 check

    - name: Static Analysis
      if: |
        github.event.commits
        && !startsWith(github.event.commits[0].message, 'WIP')
        && runner.os == 'macOS'
        && startsWith(github.ref, 'refs/heads/feature/')
      run: |
        make analyze
